import bcrypt from 'bcryptjs';

const data={
    users: [
        {
            name:'Federico',
            email:'morabitofj@gmail.com',
            password: bcrypt.hashSync('1234', 8),
            isAdmin: true,
        },
        {
            name:'Juan',
            email:'user@gmail.com',
            password: bcrypt.hashSync('1234', 8),
            isAdmin: false,
        },
    ],
    products:[
        {
            _id: '1',
            name: 'Remote Control',
            category: 'TV things',
            image: '/images/p1.jpg',
            price: 1500,
            countInStock: 10,
            brand: 'Xiaomi',
            rating: 4,
            numReviews: 15,
            description: 'high quality controller',
        },
        {
            _id: '2',
            name: 'Freezer',
            category: 'Kitchen',
            image: '/images/p2.jpg',
            price: 60000,
            countInStock: 20,
            brand: 'Liliana',
            rating: 4,
            numReviews: 15,
            description: 'The ultimate freezer',
        },
        {
            _id: '3',
            name: 'Remote Control',
            category: 'TV things',
            image: '/images/p3.jpg',
            price: 2000,
            countInStock: 0,
            brand: 'Samgung',
            rating: 4,
            numReviews: 15,
            description: 'high quality controller',
        },
        {
            _id: '4',
            name: 'Sony TV',
            category: 'TV things',
            image: '/images/p4.jpg',
            price: 40000,
            countInStock: 7,
            brand: 'Sony',
            rating: 5,
            numReviews: 25,
            description: 'high quality screen',
        },
        {
            _id: '5',
            name: 'Remote Control',
            category: 'TV things',
            image: '/images/p5.jpg',
            price: 1500,
            countInStock: 12,
            brand: 'Xiaomi',
            rating: 4,
            numReviews: 15,
            description: 'high quality controller',
        },
        {
            _id: '6',
            name: 'Remote Control',
            category: 'TV things',
            image: '/images/p6.jpg',
            price: 1500,
            countInStock: 150,
            brand: 'Xiaomi',
            rating: 4,
            numReviews: 15,
            description: 'high quality controller',
        },
    ]
};

export default data;